remote_theme: "mmistakes/minimal-mistakes@4.21.0"
title: "AidoP's Blog"
masthead_title: "Blog"
subtitle: "A loose collection of thoughts"
name: "AidoP"
url: "https://aidop.github.io"
baseurl: "/blog"
repository: "AidoP/blog"
minimal_mistakes_skin: "dark"
timezone: Australia/Perth

plugins:
    - jekyll-include-cache
